Database: #настройка базы данных, достпные: MySQL, MariaDB, SQLite
  Type: sqlite
  sqlite:
    file: plugins/pncTGReward/data.db
  MariaDB/MySQL:
    host: 127.0.0.1
    port: 3306
    database: tgreward
    user: root
    password: ''

#Настройка бота в тг
Telegram:
  token: "PUT_YOUR_BOT_TOKEN"
  campaign-id: "default"
  rate-limit-seconds: 3

#Настройка наград
Reward:
  one-time: false #Использовать награду единоразово?
  cooldown: 3600 #Если one-time == false, какой кулдаун использовать?
  Commands:
    - "p give [player] 100"

#Сообщения в игре
Messages:
  prefix: "<gray>[<light_purple>TG</light_purple>]</gray> "
  already-linked: "<red>Этот телеграм уже привязан к другому нику.</red>"
  name-already-linked: "<red>Этот ник уже привязан к другому телеграму.</red>"
  claimed-already: "<yellow>Награда по кампании уже получена.</yellow>"
  player-not-found: "<red>Игрок <white><name></white> не найден.</red>"
  success-chat: "<green>Награда выдана! Спасибо за участие.</green>"
  console-claim-log: "Выдана награда: tg=<tg_id> uuid=<uuid> name=<name> campaign=<campaign>"

#сообщения бота в тг
  telegram:
    usage:
      - "Использование: */reward <ник>*"
    ratelimited:
      - "Подождите немного и повторите"
    claimed-already:
      - "❌ Уже получали награду по этой кампании."
    player-not-found:
      - "❌ Игрок не найден: <name>"
    name-already-linked:
      - "❌ Этот ник уже привязан к другому Telegram."
    tg-already-linked:
      - "❌ Этот Telegram уже привязан к другому нику."
    reward-success:
      - "✅ Награда выдана игроку <name>"
    cooldown:
      - "❌ Подождите ещё <time>"

#Тайтл, который вылазиит при получении награды
Title:
  enabled: true
  main: "<gradient:#8a2be2:#ff66ff>Награда получена!</gradient>"
  sub: "<white>Забегай почаще :)</white>"
  fadein: 10
  stay: 50
  fadeout: 10

#Настройка звука при выдаче награды
Sound:
  enabled: true
  name: "ENTITY_PLAYER_LEVELUP"
  volume: 1.0
  pitch: 1.0

#настройка форматирования времени
formating_time:
  time-one: "%s д. %s ч. %s м. %s с."
  time-two: "%s ч. %s м. %s с."
  time-three: "%s м. %s с."
  time-four: "%s с."

#Настройка отображения плейсхолдеров
placeholders:
  status:
    yes: "<green>Привязано</green>"
    no: "<red>Не привязано</red>"
  cooldown:
    yes: "<yellow><time></yellow>"
    no: "<green>Вы можете забрать награду</green>"